[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
oylpus_dao_smart_contract = "B8i8uoj4JGaJqiYaaEHQFdrHUVFEpgvtkFpAvbZxLbML"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/elpis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
